# -*- coding: utf-8 -*-
"""Diagonistic 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbqKHGLb2uTBT77IFY2hxlqgRxplkrPH
"""

#input msg = 'pppppppjkkkkkklllaaaaauooott'
#compress msg

def compress_message(msg):
  compressed_msg = ""
  count = 1

  for i in range(1, len(msg)):
    if msg[i] == msg[i-1]:
      count += 1
    else:
      if count > 1:
        compressed_msg += msg[i-1] + str(count)
      else:
        compressed_msg += msg[i-1]
      count = 1

  if count > 1:
      compressed_msg += msg[-1]+ str(count)
  else:
    compressed_msg += msg[-1]

  return compressed_msg

msg = 'pppppppjkkkkkklllaaaaauooott'
compressed_msg = compress_message(msg)
print(compressed_msg)

#Output = p7jk6l3a5uo3t2

